# site properties and page defaults
title: Wolkowicz Workspace
subtitle: U-CARE Lab
description: The Wolkowicz Workspace (User-Centered Assistive and Rehabilitative Robotics Engineering - U-CARE) is dedicated to advancing human-centered innovation in assistive and rehabilitative technologies. Our team collaborates with wheelchair useres, clinicians, and students to design, prototype, and evaluate next-generation robotic systems that enhance mobility, support rehabilitation, and promote independence.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: kelilah_wolkowicz@uml.edu
  orcid: 0000-0002-9788-3502
  google-scholar: https://scholar.google.com/citations?hl=en&user=DQwmmCIAAAAJ&view_op=list_works&gmla=AH8HC4xoJcocnUUAt5nhquEd5L68o8iax0b2kN8KB5YTxXQh0JIwXhQEpQPubVqLDAVDX7e7KqKrvX-JdND6HvPn
  github: kelilahw
  twitter: kelilahw
  youtube: kelilahw

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
